xen/vpci: unused label fixup
If built without CONFIG_HAS_VPCI_GUEST_SUPPORT, we would end up with this error:

drivers/vpci/vpci.c: In function ‘vpci_assign_device’:
drivers/vpci/vpci.c:200:1: error: label ‘out’ defined but not used [-Werror=unused-label]
  200 | out:
      | ^~~